name: fairy_tale_app
description: ""
homepage: www.shoh.dev
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  simple_gesture_detector: ^0.2.1
  just_audio: ^0.9.46
  supabase_flutter: ^2.8.3

  # Freezed
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # myspace
  myspace_design_system:
    path: /Users/shoh/Documents/github/personal/myspace/packages/myspace_design_system
  myspace_data:
    path: /Users/shoh/Documents/github/personal/myspace/packages/myspace_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true